# -*- coding: utf-8 -*-
"""Decision tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRZgA2h1zDcybARCUFnp7CZzaf8BFl9s
"""

# import libraries
import pandas as pd
data = pd.read_csv('decisiontreeAdultIncome.csv')

# check the missing values
data.isnull().sum(axis=0)

# check the data types
data.dtypes

# create the dummies variables
data_prep = pd.get_dummies(data, drop_first=True)

data_prep.shape

# create the x and y variable
x = data_prep.iloc[:,:-1]
y = data_prep.iloc[:,-1]

# create the train and test data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=1234, stratify=y)

# import DecisionTreeClassifier from sklearn
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=1234)
dtc.fit(x_train,y_train)

y_predict = dtc.predict(x_test)
score = dtc.score(x_test,y_test)

# Evalute the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_predict)

cm